services:
  - type: worker
    name: pultolovbot
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TOKEN
        sync: false

